---
- name: Converge
  hosts: all
  #become: true

  pre_tasks:
    - name: Update apt cache.
      apt:
        update_cache: true
        cache_valid_time: 600
      when: ansible_os_family == 'Debian'

    - name: Ensure build dependencies are installed.
      yum:
        name:
          - logrotate
          - systemd-sysv
        state: present
      when: ansible_os_family == 'RedHat'

  roles:
    - role: geerlingguy.varnish

  post_tasks:
    - name: Check the installed Varnish version.
      command: varnishd -V
      register: varnish_version_output
      failed_when: "varnish_version not in varnish_version_output.stderr"
      changed_when: false
      tags: ['skip_ansible_lint']

    - name: Verify Varnish is running on port 80.
      shell: 'curl -sI localhost:80 | grep -q "Via: .* varnish"'
      changed_when: false
      tags: ['skip_ansible_lint']
