---
- name: Converge
  hosts: all
  become: true

  vars:
    varnish_version: "6.0"

  pre_tasks:
    - name: Ensure build dependencies are installed.
      yum:
        name:
          - logrotate
          - systemd-sysv
        state: present
      when: ansible_os_family == 'RedHat'

  roles:
    - role: geerlingguy.varnish

  post_tasks:
    - name: Check the installed Ansible version.
      command: varnishd -V
      register: varnish_version
      failed_when: "'6.0' not in varnish_version.stderr"
      changed_when: false
      tags: ['skip_ansible_lint']

    - name: Verify Varnish is running on port 80.
      shell: 'curl -sI localhost:80 | grep -q "Via: .* varnish"'
      changed_when: false
      tags: ['skip_ansible_lint']
